version: "3.5"

services:

#  pythonapiframework:
#    hostname: api
#    container_name: local-api
#    image: pythonapiframework
#    depends_on:
#      - dynamo
#    networks:
#      - local-dynamodb
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    ports:
#      - "9001:9001"

  dynamo:
    hostname: dynamodb
    container_name: local-dynamodb
    image: amazon/dynamodb-local
    networks:
      - local-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."

networks:
  local-dynamodb:
    name: local-dynamodb

volumes:
  dynamodata: {}
